language: ruby
rvm:
- 2.3.3

install: gem install jekyll html-proofer
script: bundle exec jekyll build && bundle exec htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

exclude: [vendor]

sudo: false
