# Site Settings
title: Lorem Ipsum
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pharetra condimentum nunc, sit.
keywords: ""
lang: en_US
timezone: America/Sao_Paulo

# Copyright Settings
# Note: the values of these variables are regarding the **content** of the site,
# not the theme data.
copyright:
  author: Author Name
  year: Year
  license:
    name: License name
    url: http://where.the.license.is

# User Settings
username: User
user_title: Real Name
email: your@email.here
# The social links bars offer support to a variety of social medias. If you don't
# have any of the listed bellow, or if you want to omit it for any reason, simply
# delete the line of the property, and it won't be rendered.
social:
  twitter: twitter
  reddit: reddit        # Format your reddit name as either 'u/username' or 'r/subreddit', as you see fitter for your wishes.
  github: github
  gplus: googleplus     # Omit the '+' char, it is added to the links already.
  instagram: instagram
  hackernews: hackernews
  disqus: disqus
  linkedin: linkedin
  facebook: facebook
google-analytics_code: UA-########-#

###############################
#        META SETTINGS        #
#        -------------        #
# The settings below here are #
# required by the theme, for  #
# it to work.                 #
# Change them at your own     #
# risks.                      #
###############################

# Theme Settings
name: Hepta
baseurl: ""
url: ""
permalink: /posts/:year/:month/:day/:title.html

# Collections Settings
collections:
  repos:
    output: true
    permalink: /projects/:name

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
gems:
  - jemoji
sass:
  style: compressed

# Meta Settings
exclude: ["readme.md", "license.md", "changelog.md", "res", "appveyor.yml", "buddy.yml"]
include: [".htaccess"]
